# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    Symfony\Component\Security\Core\User\User: sha512
    PPE\UserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    main:
        id: fos_user.user_provider.username_email
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  firewalls:
    dev:
       pattern: ^/(_(profiler|wdt)|css|images|js)/
       security: false
    admin:
       pattern:       ^/admin/
       provider:      main
       form_login:
          check_path: /admin/fos_user_security_login
          login_path: /admin/fos_user_security_check
       anonymous:     false
       logout:
          path:       /admin/fos_user_security_logout
          target:     /admin/fos_user_security_login
    main_login:
      pattern:        ^/login$
      anonymous:      true
      provider:       main
    main:
      pattern:        ^/
      anonymous:      true
      provider:       main
      form_login:
        login_path:   fos_user_security_login
        check_path:   fos_user_security_check
      logout:
        path:         fos_user_security_logout
        target:       fos_user_security_login
      remember_me:
        secret:       "%secret%"


        # disables authentication for assets and the profiler, adapt it according to your needs





            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
