services:
    ppe.registration.type:
        class: PPE\UserBundle\Form\Type\RegistrationFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: ppe_user_registration }
